# permissions for end users to edit guesstbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: guesstbook-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test1
    app.kubernetes.io/part-of: test1
    app.kubernetes.io/managed-by: kustomize
  name: guesstbook-editor-role
rules:
- apiGroups:
  - webapp.hl1.com
  resources:
  - guesstbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.hl1.com
  resources:
  - guesstbooks/status
  verbs:
  - get
