---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.hl1.com
  resources:
  - guesstbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.hl1.com
  resources:
  - guesstbooks/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.hl1.com
  resources:
  - guesstbooks/status
  verbs:
  - get
  - patch
  - update
